### ISSUE TITLE
Unable to select alternative user credentials

### ISSUE THREAD

**Issue by bkeyser** [jaws-framework/JAWS#106]
Using v1.0 branch as of September 13.

When attempting to select a non-default profile user by choosing the number 2 in the example below, the JAWS cli gives the following error

```bash
JAWS: Select a profile for your project: 
  > 1) default
    2) jaws_user
/projects/aws-demo/JAWS/lib/utils/cli.js:175
      } else if (key.name == 'up' && Select.state.index > 1) {
                    ^

TypeError: Cannot read property 'name' of undefined
    at ReadStream.<anonymous> (/projects/aws-demo/JAWS/lib/utils/cli.js:175:21)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
    at emitKey (/projects/aws-demo/JAWS/node_modules/keypress/index.js:406:12)
    at ReadStream.onData (/projects/aws-demo/JAWS/node_modules/keypress/index.js:48:14)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at TTY.onread (net.js:523:20)
```

**Comment by ac360** [comment]
@bkeyser What operating system are you using?

**Comment by dekz** [comment]
This is reproducible if you try to keypress '2' then 'Enter', rather than use the `Up` `Down` navigational arrows.

**Comment by bkeyser** [comment]
I am using the same OS as deck:  OS X 10.10.5 and the error was generated when I pressed the number 2.

**Comment by ac360** [comment]
Thanks all!  The numbers were a design touch but unnecessary.  I've removed them in v0.9.2.  Please upgrade your `jaws-framework` module.
