### ISSUE TITLE
Error on jaws new

### ISSUE THREAD

**Issue by dekz** [jaws-framework/JAWS#107]
```
> jaws new action users create -b                                                                                                                                   
/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at CMD.<anonymous> (/Users/jacob/.node/lib/node_modules/jaws-framework/lib/commands/new_action.js:99:25)
    at CMD.tryCatcher (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/util.js:26:23)
    at CMD._createSkeleton (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/method.js:15:34)
    at CMD.tryCatcher (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jacob/.node/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by ac360** [comment]
@dekz Are you using `jaws-framework` v0.9.1?

**Comment by dekz** [comment]
bleh I was in the wrong working directory at that stage.

Maybe a check for `jaws.json` or `jaws-cf.json` and a nice user message.

v1.0

**Comment by doapp-ryanp** [comment]
I added some validation logic (including this check) in https://github.com/jaws-framework/JAWS/commit/9b8c2ed60281c92491832c3aac94b059e89fc805

Will be coming on 0.9.2 release here soon
