### ISSUE TITLE
Creation of aws credentials files does not function

### ISSUE THREAD

**Issue by boushley** [jaws-framework/JAWS#152]
When running jaws on a fresh system without the admin credentials setup yet you get the following error while after filling out all of the information for `jaws new project`

```
Error: ENOENT: no such file or directory, open '/Users/boushley/.aws/credentials'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.readFileSync (/Users/boushley/projects/jaws/node_modules/aws-sdk/lib/util.js:102:35)
    at Object.module.exports.profilesMap (/Users/boushley/projects/jaws/lib/utils/aws.js:73:38)
    at /Users/boushley/projects/jaws/lib/commands/new_project.js:231:37
    at tryCatcher (/Users/boushley/projects/jaws/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/boushley/projects/jaws/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/boushley/projects/jaws/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/Users/boushley/projects/jaws/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/boushley/projects/jaws/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/boushley/projects/jaws/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

I've got a branch that works past that [on my fork](https://github.com/boushley/JAWS/tree/fix-credential-creation) however it then runs into a problem where the `.aws/credentials` file gets created but is empty.

**Comment by boushley** [comment]
Looks like `fs.appendFileSync` isn't behaving as we expect.

**Comment by boushley** [comment]
Tracked down the issue, `util.writeFile` isn't synchronous and we were treating it as such. Opened #153 that should resolve this.
