### ISSUE TITLE
Endpoint deploy command not working, but dash command does

### ISSUE THREAD

**Issue by shortjared** [jaws-framework/JAWS#161]
I may have something configured incorrectly. It looks like regions is not getting pulled out of the Jaws json perhaps?

This was originally built with JAWS v1.1 new project command, could that cause the issue?

Let me know if more details are needed.

```
> jaws --version
1.2.1
> jaws tag --list-all
[ '/vagrant/projectJaws/back/aws_modules/sso/providers/awsm.json' ]
> jaws deploy --tags lambda
JAWS: Lambda Deployer:  Choose a stage:
  >     
JAWS: Lambda Deployer:  Packaging "lSsoProviders"...
JAWS: Lambda Deployer:  Saving in dist dir /tmp/lSsoProviders@1443289516470
JAWS: Getting ENV file from S3 bucket: ************************ in us-east-1
JAWS: Lambda Deployer:  Bundled file written to /tmp/lSsoProviders@1443289516470/bundled.js
JAWS: Lambda Deployer:  Minified file written to /tmp/lSsoProviders@1443289516470/minified.js
JAWS: Lambda Deployer:  Compressed lambda written to /tmp/lSsoProviders@1443289516470/package.zip
JAWS: Lambda Deployer:  Uploading lSsoProviders
JAWS: Running CloudFormation lambda deploy...
JAWS: Lambda Deployer:  Done deploying lambdas in us-east-1
JAWS: Lambda Deployer:  Successfully deployed lambdas to the requested regions!
> jaws deploy --tags endpoint
JAWS: Select a stage to deploy to:
  > dev
    staging
/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

TypeError: Cannot read property 'length' of undefined
    at CMD.<anonymous> (/usr/lib/node_modules/jaws-framework/lib/commands/deploy_endpoint.js:163:14)
    at CMD.tryCatcher (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/util.js:26:23)
    at CMD._promptRegions (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/method.js:15:34)
    at CMD.tryCatcher (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/jaws-framework/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
> cat jaws.json
{
  "name": "projectJaws",
  "version": "0.0.1",
  "location": "https://github.com/...",
  "author": "",
  "description": "",
  "stages": {
    "dev": [
      {
        "region": "us-east-1",
        "iamRoleArnLambda": "arn:aws:iam::****************:role/dev-projectJaws-r-IamRoleLambda-**********",
        "iamRoleArnApiGateway": "arn:aws:iam::****************:role/dev-projectJaws-r-IamRoleApiGateway-**********",
        "restApiId": "**********"
      }
    ],
    "staging": [
      {
        "region": "us-east-1",
        "iamRoleArnLambda": "arn:aws:iam::**********:role/staging-projectJaws-r-IamRoleLambda-**********",
        "iamRoleArnApiGateway": "arn:aws:iam::**********:role/staging-projectJaws-r-IamRoleApiGateway-**********"
      }
    ]
  },
  "jawsBuckets": {
    "us-east-1": "**********"
  }
}
> jaws dash
JAWS: Dashboard for project "projectJaws"
 -------------------------------------------
 Project Summary
 -------------------------------------------
    Stages:
       dev us-east-1
       staging us-east-1
    Lambdas: 1
    Endpoints: 1
 -------------------------------------------
 Select Resources To Deploy
 -------------------------------------------
    sso/providers
      L) lSsoProviders
      E) /sso/providers/{provider} - GET
    - - - - -
  >   Deploy Selected -->
JAWS: Choose a stage:
  > 1) dev
    2) staging
JAWS: -------------------------------------------
JAWS:  Dashboard:  Deploying Lambdas...
JAWS: -------------------------------------------
JAWS: No selected Lambdas to deploy.
JAWS: -------------------------------------------
JAWS:  Dashboard:  Deploying Endpoints...
JAWS: -------------------------------------------
JAWS: Endpoint Deployer:  Deploying endpoint(s) to region "us-east-1"...
JAWS: Endpoint Deployer:  "dev - us-east-1": found 1 endpoints to deploy
JAWS: Endpoint Deployer:  "dev - us-east-1": found existing REST API on AWS API Gateway with ID: **********
JAWS: Endpoint Deployer:  "dev - us-east-1": found 4 existing resources on API Gateway
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": created method: GET
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": created integration with the type: AWS
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": removed existing lambda access policy statement
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": created new lambda access policy statement
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": created method response
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": created method response
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": created method integration response
JAWS: Endpoint Deployer:  "dev - us-east-1 - sso/providers/{provider}": created method integration response
JAWS: Endpoint Deployer:  Endpoints for stage "dev" successfully deployed to API Gateway in the region "us-east-1". Access them @ https://**********.execute-api.us-east-1.amazonaws.com/dev/
JAWS: -------------------------------------------
JAWS:  Dashboard:  Deployments Completed
JAWS: -------------------------------------------
```

**Comment by ac360** [comment]
@shortjared  Good catch!  Fixing this right now..

**Comment by ac360** [comment]
@shortjared Could you try JAWS V1.2.2 and let me know if it works now?

**Comment by ac360** [comment]
@shortjared Feel free to re-open this if it's not working.  I will fix it asap :)

**Comment by shortjared** [comment]
Perfect. Fix is good. Really looking forward to catching your reinvent session!

**Comment by ac360** [comment]
Thanks @shortjared It would be great to meet you.  Enjoy JAWS :)
