### ISSUE TITLE
(v1.3) Creation of new stage throws exception

### ISSUE THREAD

**Issue by Nopik** [jaws-framework/JAWS#182]
During stage creation I'm getting `[TypeError: Cannot read property 'filter' of undefined]` printed on console. Stage creation succeeds, though. After brief analysis I've seen that stage validation tries to read .env file from s3 bucket, but since that bucket is not present yet (as we are about to create it), it fails. Interestingly, everything proceeds even if _validate() fails, which seems like problem on its own. But, to the point.

After short investigation, the exact problem is in https://github.com/jaws-framework/JAWS/blob/v1.3/lib/utils/index.js#L304 as `projectStageObj` is undefined, due to no stage in `projectJawsJson.stages`. Clearly simple `if( projectStageObj )` will fix the problem, but the whole thing will throw few lines below, because region will not be set. So, instead of providing pull request with half of the fix or doing some bigger refactoring, I've decided to open this issue and ask how it should be fixed in the first place.

Stack trace (line numbers might differ a bit, since I've been adding console.log statements):

```
{ [JawsError: Could not find region us-east-1]
  name: 'JawsError',
  message: 'Could not find region us-east-1',
  messageId: 1 } 'JawsError: Could not find region us-east-1
at Object.exports.getProjRegionConfigForStage (/Users/nopik/Documents/Projects/JAWS/lib/utils/index.js:313:11)
    at Jaws.getJawsBucket (/Users/nopik/Documents/Projects/JAWS/lib/index.js:125:26)
    at Jaws.<anonymous> (/Users/nopik/Documents/Projects/JAWS/lib/index.js:91:22)
    at Jaws.tryCatcher (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/util.js:26:23)
    at Jaws.getEnvFile (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/nopik/Documents/Projects/JAWS/lib/commands/env.js:33:27
    at tryCatcher (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/nopik/Documents/Projects/JAWS/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)'
```

**Comment by ac360** [comment]
Should be fixed in 6bedcc2a1b8068e4030a215bf6897e20fef4d597

Re-open if not.
