### ISSUE TITLE
No such file "event.json". What am I doing wrong?

### ISSUE THREAD

**Issue by vlamic** [jaws-framework/JAWS#263]
Hi guys,

It's a great framework you came up with. I'm really looking forward into it and believe it's going to get a great future. I'm evaluating it and getting an error below when trying do run a command "jaws run". Also, if I deploy it, I get an error "ReferenceError: event is not defined" when running my lambda function. Is it something I'm doing wrong? Thanks!

fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/vlad/projects/myNewApi/event.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.exports.readAndParseJsonSync (/usr/local/lib/node_modules/jaws-framework/lib/utils/index.js:337:24)
    at Object.module.exports.run (/usr/local/lib/node_modules/jaws-framework/lib/commands/run.js:38:21)
    at Command.<anonymous> (/usr/local/lib/node_modules/jaws-framework/bin/jaws:134:22)
    at Command.listener (/usr/local/lib/node_modules/jaws-framework/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/jaws-framework/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/jaws-framework/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/jaws-framework/bin/jaws:351:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by vlamic** [comment]
Ah, ok. I was executing it from within the main root project dir. Now when I'm running it from the lambda dir, I just get "event is not defined".

**Comment by vlamic** [comment]
Sorry for disturbing, I've found an issue :)
