### ISSUE TITLE
uglifyier fails on bundled.js and prevents deployment of lambda

### ISSUE THREAD

**Issue by jerzyn** [jaws-framework/JAWS#288]
Hi,
when I am trying to deploy my lambda to amazon (jaws dash) I am getting an error from uglyfier on processing the bundled.js. The code is not related to the code I have written, but seems to be related to the ES6 parts in the generated bundle. I have tried to run uglyfier on my own and after changing let to var it does compile correctly. I have node v.5.0.0, jaws v1.3.3 and npm v3.3.6. 
The error is the following:
JAWS: -------------------------------------------  
JAWS:  Dashboard:  Deploying Lambdas...  
JAWS: -------------------------------------------  
JAWS: Lambda Deployer:  Packaging "lApiPick"...  
JAWS: Lambda Deployer:  Saving in dist dir /tmp/lApiPick@1446571600666  
JAWS: Getting ENV file from S3 bucket: jaws.dev.useast1.myapp-vy4cvohz.com in us-east-1  
JAWS: Lambda Deployer:  Bundled file written to /tmp/lApiPick@1446571600666/bundled.js  

undefined:1516
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1508:18)
    at js_error (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1516:11)
    at croak (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2008:9)
    at token_error (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2016:9)
    at expect_token (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2029:9)
    at expect (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2032:36)
    at regular_for (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2262:9)
    at for_ (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2258:16)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2140:24)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2055:24)
    at block_ (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2335:20)
    at eval (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2308:25)
    at function_ (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2313:15)
    at expr_atom (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2521:24)
    at maybe_unary (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2691:19)
    at expr_ops (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2726:24)
    at maybe_conditional (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2731:20)
    at maybe_assign (eval at <anonymous> (/usr/lib/node_modules/jaws-framework/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2755:20)

Thanks!

**Comment by jerzyn** [comment]
Forgot to add, that this change worked on already generated bundled.js (I was running uglyfier locally). During deployment it still fails.

**Comment by doapp-ryanp** [comment]
uglify/minify does not work for all JS.  You can disable minify by setting `lambda.package.optimize.minify` to `false`

Ex (obv set this to false):
https://github.com/awsm-org/awsm-images/blob/master/awsm/thumbnail/awsm.json#L11

**Comment by picsoung** [comment]
That's something we've tried before, with no success :(

**Comment by Kenny-House** [comment]
Running into this problem as well.

Will try to isolate the issue and provide an example of where this fails.

Setting `lambda.package.optimize.minify` to `false` does not prevent the issue.

**Comment by Kenny-House** [comment]
Update: The [line in deploy_lambda.js that should enable / disable minification](https://github.com/jaws-framework/JAWS/blob/89add26d01a0eb64a86016768814507410073da2/lib/commands/deploy_lambda.js#L658) appears to check the `_this._awsmJson.lambda.package.optimize.exclude` property instead of the `_this._awsmJson.lambda.package.optimize.minify`.

Updating the conditional to instead check `_this._awsmJson.lambda.package.optimize.minify` bypasses UglifyJS.

This seemed to present a different problem, however, where the buffer returned from browserify ([resolved in the promise if minify is disabled](https://github.com/jaws-framework/JAWS/blob/89add26d01a0eb64a86016768814507410073da2/lib/commands/deploy_lambda.js#L670)) needs to be converted to a string. Changing the line to `resolve(bundledBuf.toString());` allows the build to continue.
